helm/chart-releaser

.goreleaser.yml
Missed that when moving from circle to goreleaser before hook
Note this is to fix https://circleci.com/gh/helm/chart-releaser/1
=> dep ensure must be run from within a known GOPATH/src

.circleci/config.yml, .goreleaser.yml
See #20, #21
There's not much visibility into goreleaser hook environments, so moving dep ensure step to circle. It's just as good here anyway.
=> Move gorelaser before hook to circle job

tag.sh
This is to avoid accidentally tagging the wrong commit if
the wrong branch is checked out.
=> Use latest upstream instead of local branch for tags

cr/cmd/index.go, cr/cmd/upload.go, pkg/config/config.go, pkg/releaser/releaser.go, pkg/releaser/releaser_test.go, pkg/releaser/testdata/repo/index.yaml
Fixes a regression that would discard an existing index file
in the charts repo and always create a new one that only
contained newly released charts.
Signed-off-by: Reinhard Naegele <unguiculus@gmail.com>
=> Fix index file creation

Dockerfile
For [CVE-2019-14697](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14697)
=> Bump Dockerfile Alpine base image to 3.10

README.md, cr/cmd/index.go, cr/cmd/upload.go, go.mod, go.sum, pkg/config/config.go, pkg/github/github.go
Address https://github.com/helm/chart-releaser/issues/14
As per https://github.com/google/go-github/blob/master/github/github.go#L296, the difference of public and enterprise github is values for `github base url` and `github upload url`.
In this PR, I just exposed two additional params for the same. The default values are also specified.
=> Added BaseURL and UploadURL for GitHub Enterprise

README.md
Some notes about using this tool with Github Enterprise and a known gotcha as noted in https://github.com/helm/chart-releaser/issues/57
=> Add note about GHE upload URL bug

cr/cmd/index.go, cr/cmd/upload.go, pkg/config/config.go, pkg/git/git.go, pkg/github/github.go, pkg/releaser/releaser.go, pkg/releaser/releaser_test.go
This adds the option to push the `index.yaml` file, either directly to the GitHub Pages branch, which is now configurable, or via pull request.
=> Add option to push to gh-pages

.github/workflows/ci.yaml, .github/workflows/release.yaml
* Install required tooling
* Create Git tag locally instead of via GitHub API so Goreleaser
can find it
=> Fix release workflow

pkg/releaser/releaser.go, pkg/releaser/releaser_test.go, pkg/releaser/testdata/empty-repo/index.yaml
Currently, the only time the `generated` field is ever written is when we invoke the `repo.NewIndexFile()` method. This means that contrary to what you would expect, the `generated` field is not updated when the index is updated.
This adds a single line change that calls `time.Now()` after we have determined that the index is to be updated, and updates the `generated` field before the index is written.
Closes #90
=> Update releaser to regenerate generated field on index update

cr/cmd/upload.go, pkg/config/config.go, pkg/releaser/releaser.go
I just ran into bug #65 with the exact same use case that the author of the bug reported. I have a repository for all the charts in my organization what I want is for a CI pipeline to automatically push the charts that have changed. I am trying to keep the CI logic simple and cr is helping me a lot but I do have the issue that not all charts are changing at the same time. What I would like is to be able to tell cr to skip charts that have a name/tag that is already released (a warning can be added).
This seems to be simple, I just added a "skip" flag and if a release already exists it just skips it.
I did not add a test yet since I would like feedback on it before moving forward. Any thoughts on this fix?
thank you for CR!!
=> Adding option to skip existing releases

pkg/github/github.go
Facing the same issue as described [here](https://github.com/tcnksm/ghr/pull/99)
The following error is being thrown when using the `chart-releaser` v1.2.0 inside a Github action in a `self-hosted` action runner (using Docker in Docker):
```
stat /path/to/release/foo-v0.0.5.tgz: use of closed file
```
Looks like a race between the file handler being closed and the `UploadReleaseAsset` being called. I would suggest to move this part into the `retry loop`.
=> Open release file in retry loop

Dockerfile
In order to run `cr index` from docker image with `--push` or `--pr` you need git.
=> bug: add git to docker image to run cr index

pkg/releaser/releaser.go
If GH fails to upload, you get errors which don't really help much, like:
```
Error: error creating GitHub release: POST https://api.github.com/repos/garethahealy/helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
Adding in the releaseName would help diagnose what's wrong.
=> Added releaseName to error returned on gh failure

Dockerfile
Add missing brackets otherwise, we need to set the entry point when running
/kind bug
Fixes: https://github.com/helm/chart-releaser/issues/126
built locally
```
$ docker run quay.io/helmpack/chart-releaser:latest upload --help
Upload Helm chart packages to GitHub Releases
Usage:
cr upload [flags]
Flags:
-c, --commit string                  Target commit for release
-b, --git-base-url string            GitHub Base URL (only needed for private GitHub) (default "https://api.github.com/")
-r, --git-repo string                GitHub repository
-u, --git-upload-url string          GitHub Upload URL (only needed for private GitHub) (default "https://uploads.github.com/")
-h, --help                           help for upload
-o, --owner string                   GitHub username or organization
-p, …
```
=> docker fix entrypoint

README.md
Adds reference for using `--skip-existing` and `CR_SKIP_EXISTING` configuration.
=> Update docs to reflect if release already exists flag from #111

README.md, cr/cmd/index.go, pkg/config/config.go, pkg/releaser/releaser.go, pkg/releaser/releaser_test.go
So far the index.yaml was loaded directly from the chart repository. In case of GitHub pages that's https://<user or org>.github.io/<repo>
The problem with this approach is that GitHub pages use a Content Delivery Network. So the index.yaml files fetched from there might be outdated as there is a delay between a git push to the gh-pages branch until the content is visible.
This delay might lead to the situation that one downloads an old index file from and updated that one instead of the most recent index.yaml.
For the grafana repository that resulted in already released charts being removed again.
- https://github.com/grafana/helm-charts/issues/783
- https://github.com/grafana/helm-charts/pull/796
This PR resolves that issue by reading the index.yaml from the gh_pages branch of the …
=> Deprecate cr index "charts-repo" flag. Instead read index.yaml from git repository

.github/workflows/ci.yaml, .gitignore, cr/cmd/docGen.go, cr/cmd/package.go, doc/cr.md, doc/cr_completion.md, doc/cr_completion_bash.md, doc/cr_completion_fish.md, doc/cr_completion_powershell.md, doc/cr_completion_zsh.md, doc/cr_index.md, doc/cr_package.md, doc/cr_upload.md, doc/cr_version.md, go.mod, go.sum, pkg/packager/packager.go
**What this PR does / why we need it**:
- add job to check if docs are up to date
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
**Special notes for your reviewer**:
=> Add command docs and job to check it

README.md, cr/cmd/upload.go, doc/cr_upload.md, pkg/releaser/releaser.go
This PR is simply added an extra line of code to warn the user that the file specified is not found.
I spent 30 minutes to understand that the release note file had to be placed inside the chart package and I ended up reading the source code. Therefore I updated the readme as well
=> Added a log if release notes are not found in chart package

pkg/packager/packager.go
Fixes: https://github.com/helm/chart-releaser/issues/225
=> Fixing registry client for packaging charts with OCI dependencies

pkg/releaser/releaser.go, pkg/releaser/releaser_test.go
Update the function used to update the index to ignore any file that does not have the chart asset file extension (.tgz). This is necessary because chart-release fails with users add another kind of files in chart release.
Fix #233
=> Ignore third party files added in the release.

.github/workflows/ci.yaml, .github/workflows/release.yaml, .golangci.yml, go.mod, pkg/releaser/releaser.go
=> upgrade to go 1.20

.github/auto-merge-deps.yml
- enable auto mergefor dependencies
This job enable the auto merge and approval in the following conditions
1. It will only run for dependabot PRs
2. If the Dependency change PR is a `minor` or `patch` the job will enable the auto merge, and if all the required ci checks passes it will merge it
3. For major changes it will do nothing
=> enable auto merge for dependencies

README.md
Add documentation about the new **cr** flag **"--pakages-with-index"** with an example with screenshots.
Add a Common Error Section
This is the updated documentation for [#123](https://github.com/helm/chart-releaser/pull/123)
=> Update Readme with --package-with-index usage (PR #123)

.github/workflows/release.yaml, .goreleaser.yml, magefile.go
These are the modifications I needed to run Actions so I could send a pull request.
=> enable contributions from forks

pkg/releaser/releaser.go, pkg/releaser/releaser_test.go
Resolves the problem [mentioned](https://github.com/helm/chart-releaser/pull/123#discussion_r1148913202) in [this](https://github.com/helm/chart-releaser/pull/123) PR
Lets say you want to upload more than one release and place it near the index file. After the first push your second push will be rejected with an error "Updates were rejected because a pushed branch tip is behind its remote". So either you need to pull changes before push another release or push all releases once in the end of upload action.
In case of pulling changes and pushing every release separately you'll face github will launch as many "pages build and deployment" actions as there are new releases you want to upload. All except one will be canceled, but the list of actions will look like a mess.
So the most efficient …
=> Peform single push on upload in case of multiple releases

.github/workflows/release.yaml, .goreleaser.yml
ass this repo/github actions does not have access to homebrew-tap repo, we need to have a PAT with that permissions, we have already that secret, will bring back that to push the formula update
see error https://github.com/helm/chart-releaser/actions/runs/12390050554/job/34584290326
=> add existing CI TOKEN to access/push brew update
