helm/chart-releaser

Gopkg.lock
cmd/index.go
cmd/root.go
cmd/upload.go
pkg/config/config.go
pkg/index/main.go
pkg/upload/main.go

* Refactor config loading to config package
* Bind flags to viper
* No longer mark flags as required so environment variables,
config files, and flags can be arbitrarily combined. Instead,
validate the final options struct
* Use CH_ prefix for environment variables

Fix viper/cobra integration

---

.gitignore
README.md
cmd/index.go
cmd/root.go
cmd/upload.go
main.go
pkg/config/config.go
pkg/index/main.go
pkg/upload/main.go

Rename from paulczar/charthub to helm/chart-releaser

---

code-of-conduct.md

Chart releaser Helm CoC

---

LICENSE
main.go
pkg/github/github.go
pkg/index/main.go
pkg/upload/main.go

Ensure correct licensing

---

pkg/upload/main.go

Change tag pattern to bypass semver precedence issue

---

.goreleaser.yml

Remove goreleaser variable expansion

---

pkg/index/main.go

This is a successor or #23 that aims to follow up #16 and #17

re: Fix tag pattern for index command

---

Dockerfile

The docker image was missing ca-certificates which caused a self-signed cert error

Fix CA issue in docker

---

README.md

Signed-off-by: Chris Hupman <chupman@apple.com>
Not a Contribution

Updating config.yaml README example to match changes in PR#37

---

Dockerfile

Bump Alpine to 3.11

---

.goreleaser.yml
README.md

Signed-off-by: Reinhard Naegele <unguiculus@gmail.com>

Add Homebrew formula

---

cr/cmd/upload.go
pkg/config/config.go
pkg/github/github.go
pkg/releaser/releaser.go
pkg/releaser/releaser_test.go

Permit specifying the target commit of a release

---

README.md
cr/cmd/index.go
cr/cmd/upload.go
pkg/config/config.go
pkg/releaser/releaser.go
pkg/releaser/releaser_test.go

Add option to specify template for release names

---

Dockerfile

Signed-off-by: David Karlsen <david@davidkarlsen.com>

chore: Update base-image

---

README.md

Update build badge for GitHub workflow

---

pkg/packager/packager.go

Add missing dependency update to package command

---

pkg/releaser/releaser.go

Exclude provenance files for index creation

---

go.mod
go.sum
pkg/github/github.go
pkg/packager/packager.go
pkg/releaser/releaser.go

Retry if a release is not yet available

---

.goreleaser.yml

Added the install section to have the correct binary name

Fix .goreleaser.yml for the homebrew tap formula

---

.github/workflows/ci.yaml
README.md

/assign @davidkarlsen @unguiculus

update branch name to be main

---

README.md
cr/cmd/index.go
pkg/config/config.go
pkg/releaser/releaser.go
pkg/releaser/releaser_test.go

add pages-index-path option

---

.goreleaser.yml

- add missing environment to be able to sign using keyless approach

add missing environment to be able to sign using keyless approach

---

.goreleaser.yml

fix docker build

---

.goreleaser.yml

- fix double tag in the manifest

fix double tag in the manifest

---

.github/workflows/ci.yaml
go.mod
pkg/git/git.go
pkg/packager/packager.go
pkg/packager/packager_test.go
pkg/releaser/releaser_test.go

- upgrade go to 1.19 and pin cosign-installer to v2

upgrade go to 1.19 and pin cosign-installer to v2

---

.goreleaser.yml
go.mod

Fixes in go module and goreleaser

Fixes in go module and goreleaser

---

go.mod
go.sum
pkg/github/github.go

update go-github dependency to v49

update go-github dependency to v49

---

README.md

Document how to deal with deps

---

pkg/git/git.go
pkg/releaser/releaser.go

DOCS fix commit-ish typo

---

go.mod

See https://github.com/helm/helm/pull/13591

Bump github.com/docker/docker
